### ISSUE TITLE
Duplicate rows in TLS / SSL Manager Interface

### ISSUE THREAD

**Issue by mohanavijay** [uw-labs/bloomrpc#103]
Whenever I add new root certificate under  TLS / SSL Manager window a new **Servier Certificate** row is created. (refer the screenshot)

Steps to reproduce:
--------------------
1) Load a proto file which is having a service and RPC definitions.
2) Open the rpc from the left panel
3) Now select the TLS option and click the Add Root Certificate option.
4) Provide the Root Certificate, Private Key, & Cert Chain and click **Done** button.
5) Select the TLS option again and notice that duplicate **Servier Certificate** row is created.

![image](https://user-images.githubusercontent.com/49723661/61949244-c7fb5200-afc7-11e9-8eff-d683547dddb5.png)

**Comment by XplittR** [comment]
Any progress on fixing this bug?

**Comment by Sovietaced** [comment]
I have updated to the latest version here but I still have about 30 duplicates rows. Where does this state reside on the filesystem and how should I clear it out?

I've even tried uninstalling and reinstalling.

**Comment by Sovietaced** [comment]
> I have updated to the latest version here but I still have about 30 duplicates rows. Where does this state reside on the filesystem and how should I clear it out?
> 
> I've even tried uninstalling and reinstalling.

If anyone else is wonder it appears to be under `~/.config/bloom-rpc-client` for linux.

**Comment by bendiknesbo** [comment]
The config files was located under `~/Library/Application Support/bloom-rpc-client` on MacOS.
