### ISSUE TITLE
Support for Interceptors

### ISSUE THREAD

**Issue by mohanavijay** [uw-labs/bloomrpc#104]
By using Interceptors, you can intercept the execution of RPC methods on both the client and the server.

Currently, there is no support for passing Interceptors using BloomRPC. 

https://kuros.in/grpc/2019/01/grpc-interceptors/

**Comment by fenos** [comment]
@mohanavijay Hi!

Could you give me a use case that you would need an interceptor to be used within the editor?

**Comment by mohanavijay** [comment]
@fenos,

The use case is to add interceptors to authorize the client accessing the gRPC services. This is explained in the below article.
https://kuros.in/grpc/2019/01/grpc-interceptors/

Hope this helps!

**Comment by fenos** [comment]
If that's the case then you don't need interceptors, You can already send authorization tokens in the metadata tabs

**Comment by mohanavijay** [comment]
@fenos,

Thanks, I haven't noticed the option to provide metadata till now.
