### ISSUE TITLE
keys that end with '-bin' must have Buffer values

### ISSUE THREAD

**Issue by tonyboxes** [uw-labs/bloomrpc#105]
Build a binary metadata to base64:
```
{
    "x-metadata-bin": "Cgh0ZXN0X2tleRIIbW9iaV9hcHAaBmRldmljZSAB"   
}
```
Get this error:
```
Error constructing the request
keys that end with '-bin' must have Buffer values
```

**Comment by fenos** [comment]
@tonyboxes interesting, thanks for pointing this out.

This will be fixed in the next coming release

**Comment by HunterEl** [comment]
Just ran into this issue as well. Thanks for the update, @fenos!

**Comment by tonyboxes** [comment]
Can you add debugging information, such as request header and response header information.

**Comment by HunterEl** [comment]
@tonyboxes 
```{
    "authorization-bin": "{insert hex string of data}"   
}
 Prompts me with the error message: 

`Error constructing the request
keys that end with '-bin' must have Buffer values`
```

**Comment by HunterEl** [comment]
for context, using a CLI tool with the same request and meta-data information works as intended.

**Comment by tonyboxes** [comment]
Please release this version？
