### ISSUE TITLE
Build from source fails on Linux

### ISSUE THREAD

**Issue by stereoit** [uw-labs/bloomrpc#106]
Hi, I am having trouble following installation from source, I am attatching build log.

[build.log](https://github.com/uw-labs/bloomrpc/files/3464731/build.log)

**Comment by fenos** [comment]
It looks very related to this issue: https://github.com/grpc/grpc-node/issues/739

Try to export `export CXXFLAGS -Wno-error` as suggested in the issue

**Comment by fenos** [comment]
Closing no reply
