### ISSUE TITLE
Support import path

### ISSUE THREAD

**Issue by kharry5** [uw-labs/bloomrpc#11]
Currently the UI will raise an error if the proto file contains an import that it can't resolve. Could the UI support specifying import paths similar to what grpcurl does with its -import-path option?

**Comment by fenos** [comment]
Great idea!

Let me see what I can do about this.
This is definitely a feature that I'd like to see in the editor too

**Comment by avrahamr** [comment]
Is there any work around for this in the meanwhile?

**Comment by fenos** [comment]
@avrahamr the work around would be to place the imported protos close to the file you are trying to load in the editor
