### ISSUE TITLE
build fails on ubuntu 19

### ISSUE THREAD

**Issue by AndreiD** [uw-labs/bloomrpc#111]
not sure if it's ubuntu 19 at fault here but here's the error log

![image](https://user-images.githubusercontent.com/542665/63654639-ae475900-c785-11e9-8862-4cf9b2c89e20.png)

**Comment by fenos** [comment]
@AndreiD I'd be glad if you could dig into this a bit more

**Comment by AndreiD** [comment]
how ? I don't know javascript...

**Comment by AndreiD** [comment]
the etiquette of open source tells that if you close an issue, you can at least add couple of words why....

**Comment by fenos** [comment]
@AndreiD Apologise i think i closed it unintentionally while i was doing a bit of cleaning up of the issues. 

The release 1.4.1 should fix the build problem

**Comment by AndreiD** [comment]
another etiquette says you should not make excuses or give explanations for what you do on your own open source project
