### ISSUE TITLE
Add support of multiple environments

### ISSUE THREAD

**Issue by abakumov-v** [uw-labs/bloomrpc#112]
Hi!

BloomRPC is very interesting tool and be cool if it will support of multiple environments (hosts) like a Postman environments - for example:
* localhost
* dev
* prelive

**Comment by fenos** [comment]
Lovely request!

**Comment by Gabri3l** [comment]
If I can add to it, I'd like to have the ability to set TLS at an environment level so that whenever I test a Request I don't have to manually set TLS for it every time. This app is absolutely great btw! I wish I had the time to help out!
