### ISSUE TITLE
No support for cyclic dependencies

### ISSUE THREAD

**Issue by SeriyBg** [uw-labs/bloomrpc#113]
I have a case when two messages have a recursive dependency. However, bloomRPC fail to parse such message.
Here is the proto file:
```
syntax = "proto3";

option java_multiple_files = true;

package com.my.package;

message Foo {
    Bar bar = 1;
}

message Bar {
    Foo foo = 1;
}

message Empty {
}

service FooService {
    rpc FooRequest (Foo) returns (Empty);
}
```

Here is the error that bloomRPC gives me:
```
{
  "error": "Error parsing the request message, please report the problem sharing the offending protofile"
}
```

I'm using bloomRPC version 1.3.1
It's strange that with the message that has recursive dependency I don't have this error:
```
message Foo {
    Foo foo = 1;
}
```

**Comment by nesobe123** [comment]
Hello @fenos, do you know when this bug will be fixed? Looking forward to your reply.

**Comment by Psykar** [comment]
A simpler repro

```
syntax = "proto3";

service CommandService {
  rpc Rpc(Parent) returns (Parent);
}

message Parent {
  Child Child = 1;
}

message Child {
  Parent Parent = 1;
}
```

Closely related to https://github.com/uw-labs/bloomrpc/issues/69
