### ISSUE TITLE
Cannot read property 'root' of undefined error

### ISSUE THREAD

**Issue by yeenow123** [uw-labs/bloomrpc#12]
I'm getting the following error when trying to import the following .proto, this is on a Mac OSX.

```
Error while importing protos
Cannot read property 'root' of undefined
```

This is my proto, which includes the service definition.  It imports the file without the service definition, but I don't see any option to specify fields.  I may just not be using it correctly, some usage documentation would be nice.

```
syntax = "proto3";

package com.someprofile;

service UserDataApi {
    rpc get(ReadRequest) returns (ReadResponse) {
    }

    rpc put(WriteRequest) returns (WriteResponse) {
    }
}

message ReadRequest {
    repeated string userIds = 1;
    repeated string fields = 2;
}

message ReadResponse {
    int64 ttl = 1;
}

message WriteRequest {
    int64 ttl = 1;
}

message WriteResponse {
    string userId = 1;
    bool status = 2;
}
```

**Comment by fenos** [comment]
Hi,

This is an interesting one, I think an edge case not covered in the editor.

From the first look at the protofile, I'm guessing that the offending line is the package name having a `dot` in the name.

Try to remove the dot from the package and try to import it again.

Thanks for reporting this, i'll be fixing this asap

**Comment by fenos** [comment]
I think those are 2 slightly different problems, they will be both fixed.

Thanks for sharing this, it helps a lot to fix the parsing issue.

As I mentioned there is some issue parsing this specific protofile, I probably guess that I forgot to cover the `map` data type. I'll be confirming this once I see the stack trace.

Apologize for the inconvenient, I'll be trying to push a fix this evening!

**Comment by fenos** [comment]
@yeenow123  👆 It will fix both of your issues! I'm preparing the release
