### ISSUE TITLE
[BUG] can not to see all contents

### ISSUE THREAD

**Issue by yangwenmai** [uw-labs/bloomrpc#120]
When I switch ^ , the should be scroll for show all contents.
![image](https://user-images.githubusercontent.com/1710912/65317150-d5027f00-dbcd-11e9-883a-c3df2d81afe6.png)

**Comment by fenos** [comment]
it should be draggable to the top, what version are you using?

**Comment by yangwenmai** [comment]
Version 1.3.1 (1.3.1.105)

**Comment by fenos** [comment]
Have you tried dragging the bar up and down?
What OS are you using?

**Comment by yangwenmai** [comment]
macOS 10.14.6

On the right no scroll bar to drag or scroll.

**Comment by fenos** [comment]
![metadatabar](https://user-images.githubusercontent.com/4754064/65494908-a7f3ec00-dead-11e9-9114-2d8c80cd7fa1.gif)

**Comment by yangwenmai** [comment]
The metadata can scroll.
The request and response can't scroll, when the metadata is unwind.

**Comment by fenos** [comment]
I think that is made on purpose, the metadata panel is positioned over the editor panels, it doesn't shrink the content when the metadata is opened.
