### ISSUE TITLE
Setting :authority headers returns Metadata key ":authority" contains illegal characters

### ISSUE THREAD

**Issue by teunis90** [uw-labs/bloomrpc#128]
Hi,

I found out via #31 that you can set custom headers. I would like to override the default `:authority` header.

Unfortunately, that results in a JSON error. Is this currently possible? If not, please consider this feature.

**Comment by fenos** [comment]
mmmh interesting, can you share how you are trying to send the header please. Did you make sure you wrapped the key and value with quotes?

**Comment by teunis90** [comment]
Sure, here is a screenshot:

![Screenshot 2019-10-09 at 11 33 26](https://user-images.githubusercontent.com/3136781/66465004-b71b9200-ea88-11e9-8f56-3940378470a7.png)

**Comment by teunis90** [comment]
In extension, if you use this as metadata input:
```
{"\:authority": "myvalue"}
```

You get this as in the response window:
```
{
  "error": "Couldn't parse JSON metadata Invalid json"
}
```

Screenshot:
![Screenshot 2019-10-09 at 11 44 42](https://user-images.githubusercontent.com/3136781/66465884-6016bc80-ea8a-11e9-89cb-a78009138605.png)

**Comment by fenos** [comment]
you'll need to escape the backslash:

```
{"\\:authority": "myvalue"}
```

**Comment by teunis90** [comment]
Hi @fenos,

Thanks for your 1.4.0 update! 

Unfortunately, I don't get this working yet. I'll still get the same error: 

Without backslash:
```
Error constructing the request
Metadata key":authority" contains illegal characters
```

With escaped backslash:
```
Error constructing the request
Metadata key"\:authority" contains illegal characters
```
The idea would be that you can connect to a IP-adres and set the `:authority` Header manually. This allows you to test without setting DNS entries or Host file entries.
