### ISSUE TITLE
Help with getting started

### ISSUE THREAD

**Issue by PaganEdwin** [uw-labs/bloomrpc#130]
Hi,

I'm a new user, and new to gRPC, the readme says: "Install the client, select your protobuf files and start making requests! No extra steps or configuration needed."

I added my server address, imported my proto file and there is no structure under my file name.  I also see nothing in the Editor and when I hit the play button, nothing happens, as opposed to in the Preview video, when test.proto is imported, a method structure appears below the file name, such as GetByAccountID, etc.  In the Editor we see the ID and when the Play button is pressed, we see the Response.  I'm not sure what I'm doing wrong?

In my proto file I have messages with strings and I have a service request that returns my message.  I've been trying for two days and I'm stuck in the same spot.  I'm wondering what I did wrong, so, I was wondering if anyone could be so kind as to direct me to any additional  documentation or videos to help me get started or point me to the right forum to ask these types of questions? Any help or direction on getting started would be greatly appreciated.

**Comment by fenos** [comment]
@PaganEdwin Hi, welcome to the gRPC ecosystem (sorry for the late reply).

If no method appear on the sidebar as the video demonstrated is because you don't have any service definition in your protobuf file

try todo the same step as you have done above using this protofile and let me know if that works:

```
syntax = "proto3";

package test;

message Test {
  string id = 1;
}

message TestRequest {

}

message TestResponse {
  string message = 1;
}

service TestService {
  rpc TestMethod(TestRequest) returns (TestResponse);
}
```

**Comment by PaganEdwin** [comment]
fenos!  You rock!  Thanks, you made my day!  I created a test directory with a new proto file, and in that file I added the above snippet of code.  There's nothing in my brackets in the Editor and in the Response, I get "error": "12 UNIMPLEMENTED: Method not found: test.TestService/TestMethod", so I think I need to work on the test.  Does my server need reflection for the test to work?
