### ISSUE TITLE
Include path setting 

### ISSUE THREAD

**Issue by risentveber** [uw-labs/bloomrpc#132]
One would like some kind of setting that will provide include path for any referenced proto file. Because of hard-coded definitions seem like a temporary solution. For example, I am'not able to use this:
```
import "google/type/money.proto"; 
```
This leads to the error:
```proto
Error while importing protos
no such Type or Enum 'google.type.Money' in Type ...
```
Maybe there should be some kind of config file in home directory e.g. `~/.bloomrpc-config` where all include paths are specified.

**Comment by risentveber** [comment]
@fenos  thank you, this way it works. Maybe one should add this feature description to readme? For me, this functionality seems undocumented.

**Comment by smnbbrv** [comment]
For people like me struggling with this problem although the path is added, please ensure that you clicked the "+" button after you selected the path in file browser.

**Comment by risentveber** [comment]
<img width="428" alt="Screenshot 2020-01-27 at 11 23 30" src="https://user-images.githubusercontent.com/6682918/73159482-a2c2da00-40f7-11ea-8af3-7e633949cf8a.png">

![image](https://user-images.githubusercontent.com/6682918/73159506-ae160580-40f7-11ea-957e-a45f07ed8967.png)
