### ISSUE TITLE
Cannot load proto file with Log message

### ISSUE THREAD

**Issue by abakumov-v** [uw-labs/bloomrpc#133]
Hi!

I have this proto file:

```proto
syntax = "proto3";
package Api.My.Custom.Log;

import "google/api/annotations.proto";

message Log {
    string request_uuid = 1;
    string message = 2;
    string level = 3;
    string stack_trace = 4;
}

service LogService {
    rpc put (LogPacket.PutRequest) returns (LogPacket.PutResponse) {
        option (google.api.http) = {
            post: "/log/put"
            body: "*"
        };
    }

    // rpc push (stream Log) returns (stream LogPacket.PushStreamInfo) {}
}

message LogPacket {
    message PutRequest {
        Log log = 1;
    }

    message PutResponse {
        oneof result {
            bool data = 1;
            Error error = 2;
        }

        message Error {
            string message = 1;
        }
    }

    message PushStreamInfo {
        int64 logs_count = 1;
    }
}
```

When I'm trying open this proto in BloomRPC - this it's opened correctly. But if I uncomment streaming method `push` then BloomRPC show me error:
```
Error while importing protos
no such type: Log
```
![image](https://user-images.githubusercontent.com/6594815/66753619-e2ddb400-ee9c-11e9-88b5-91f72469f40e.png)

Why BloomRPC cannot open proto file with streaming methods?

**Comment by jorgror** [comment]
I have the same issue. I think the cause is when package contains the same name as a message name and that message name is used in a rpc call. In your case you have Log in package name and a message type named Log which is used by push.

**Comment by jackielii** [comment]
can you try again in latest release? feel free to re-open

**Comment by abakumov-v** [comment]
@jackielii ok, thank you, I will try later. 

But I'm found a critical bug - tabs does not closed in new release! 
![image](https://user-images.githubusercontent.com/6594815/98830890-f797cd00-244b-11eb-81e9-3a433de767eb.png)

**Comment by jackielii** [comment]
I saw this as well, created #277 . to work around this, you can open the editor.json and delete the tabs section. On Linux, the config lives under: $HOME/.config/bloom-rpc-client/editor.json

**Comment by abakumov-v** [comment]
@jackielii  Hi!
Problem with error `no such type: Log` still persists on version 1.5.2
