### ISSUE TITLE
Fail to import proto file with 3rd party proto include

### ISSUE THREAD

**Issue by kazekim** [uw-labs/bloomrpc#134]
Hello, I have a problem. I try to import the protobuf file with 3rd party proto file from github.com/octofoxio/foundation/primitive/primitive.proto include but BloomRPC said 

Error while importing protos
no such Type or Enum 'foundation.primitive.String' in Type .kronos.svcs.v1.CreateRootUserIfNotExistResponse****

Here is the full of proto file I've created.

syntax = "proto3";

package kronos.svcs.v1;

option csharp_namespace = "Kronos.Svcs.V1";
option go_package = "svcsv1";
option java_multiple_files = true;
option java_outer_classname = "KronosRootConsoleApiProto";
option java_package = "com.kronos.svcs.v1";
option objc_class_prefix = "KSX";
option php_namespace = "Kronos\\Svcs\\V1";

import "entities/v1/merchant.proto";
import "github.com/octofoxio/foundation/primitive/primitive.proto";

// KronosRootConsoleApi highest permission level API
// Root API responsible for the system configuration
// and some credential in the system.
service KronosRootConsoleAPI {
  // CreateMerchantUser create new merchant user with API credentials.
  rpc CreateMerchant(CreateMerchantRequest) returns (CreateMerchantResponse);
  // CreateRootUserIfNotExist create new root user if not exist in database.
  rpc CreateRootUserIfNotExist(CreateRootUserIfNotExistRequest) returns (CreateRootUserIfNotExistResponse);
}

message CreateMerchantRequest {
  string merchant_id = 1;
  string display_name = 2;
  string token = 3;
}

message CreateMerchantResponse {
  entities.v1.Merchant merchant = 1;
}

message CreateRootUserIfNotExistRequest {}

message CreateRootUserIfNotExistResponse {
  bool is_new_root_user_created = 1;
  foundation.primitive.String username = 2;
  foundation.primitive.String password = 3;
}

The package has been loaded in my go workspace and it works normally when I test in cmd line.
Do you have any suggestion?

**Comment by kferrone** [comment]
Have you tried downloading the `primitive.proto` to local folder? Maybe put alongside Googles well known types. May not be best solution but it might work.

**Comment by kazekim** [comment]
You means copy it into the same directory with the proto file I want to open in bloomrpc, Right?

**Comment by fenos** [comment]
You'd be probably looking at using the `import path` functionality of bloomrpc which works exactly like the `-I` or `--import_path` flag of the protoc compiler.
