### ISSUE TITLE
Chocolatey package for deployment

### ISSUE THREAD

**Issue by npuc85** [uw-labs/bloomrpc#135]
I would like add BloomRPC to a setup script we have to get new dev machines setup. We use Windows. The best option I can come up with right now is to hard code a URL to a specific version of a windows installer .exe file. But I have a few problems with that

1. It is hard coded to a specific version, would require manually updating the script to install newer versions.
2. There don't appear to be any documented command line arguments for the installer, to have it run in silent mode, for example. Whenever I run the installer a UI instantly popups up that says its installing and when it's finished BloomRPC opens. I'd like to install it without a UI and not have it automatically open upon installation.

Can you create a chocolatey package so people could do something like `choco install bloomrpc` and it'll just install whatever the latest version is and not open it?

**Comment by fenos** [comment]
@npuc85 Hi, i haven't worked with `Chocolatey` package manager before.
If you'd like please go ahead with creating a package within that registry, but would be also great if you could keep it up to date as new releases come along

**Comment by Daniel15** [comment]
It's pretty straightforward to make a Chocolatey package. Here's the config we use for Yarn:
https://github.com/yarnpkg/yarn/blob/master/resources/win-chocolatey/yarn.nuspec
https://github.com/yarnpkg/yarn/blob/master/resources/win-chocolatey/tools/chocolateyinstall.ps1.in

You could likely use "GitHub Actions" (if you have access to the beta) or AppVeyor to automate it upon release.

> There don't appear to be any documented command line arguments for the installer, to have it run in silent mode, for example.

The installer appears to be build using NSIS, which uses `/S` for silent mode.

**Comment by fenos** [comment]
@Daniel15 can you PR please

**Comment by Daniel15** [comment]
Unfortunately I won't have any free time in the next few weeks 😞  I can look into it once I have more time.

**Comment by biqas** [comment]
HI,

any update on this?

**Comment by pnquest** [comment]
@fenos I just manually created a chocolatey package that just downloads the installer from the releases url and then runs the installer. I have it working well locally, but have not yet published it to the community repo. 

1. Do I have your blessing to push it to the community repo? I would like to make you an administrator of the package as well (and removing myself once we get this working if you prefer).
2. Manual upkeep for this would be pretty easy,  but I would love to discuss incorporating this into your release pipeline. Is that something you would be open to?
3. Would you like to keep the package files in this repo somewhere? It is just a nuspec (xml) file and a couple powershell scripts. Happy to submit a PR with them.

**Comment by pnquest** [comment]
In the interests of time I have gone ahead and published what I had https://chocolatey.org/packages/bloomrpc/ I think it will be available in a couple of hours. I published it as `1.4.1-beta` so that everyone can test it on things other than my personal machine and make sure it works before I publish the final version. 

I am keeping the source in a [different repo for now](https://github.com/pnquest/bloom-rpc-choco-package)

@Daniel15 @biqas @npuc85 -- can you try this out once it becomes available and make sure it works for you?

@fenos -- if there is anything you want me to change about how the package works, please let me know.

**Comment by pnquest** [comment]
I have now released a full version of this package [here](https://chocolatey.org/packages/bloomrpc). If you are using the enterprise version of chocolatey with the service account installs you will need to add the `--run-actual` flag in order to properly install.

**Comment by jackielii** [comment]
Thanks, would be good to send a PR to include this in the pipeline
