### ISSUE TITLE
BloomRPC is not sending grpc-encoding header

### ISSUE THREAD

**Issue by oneslash** [uw-labs/bloomrpc#140]
Following up https://github.com/grpc/grpc-go/issues/3142

Image:
![image](https://user-images.githubusercontent.com/15870134/68211437-dd751480-ffd7-11e9-91da-6612a1fe5537.png)

**Comment by fenos** [comment]
@oneslash thanks for opening the issue.

Could you point me to any doc that is mentioning the `grpc-encoding` header?
Since BloomRPC uses `node-grpc` i though it would forward it automatically, but happy to understand why is not sent and include it

**Comment by oneslash** [comment]
@fenos I have created a documentation in https://github.com/grpc/grpc-node/pull/1161 for explaining how to add them to the client params.
