### ISSUE TITLE
canceling stream by BloomRPC

### ISSUE THREAD

**Issue by NUnitTester** [uw-labs/bloomrpc#144]
I have a question about BloomRPC and the following example:
service Progressor {
	rpc RunHistory (google.protobuf.Empty) returns (stream HistoryResponse);
}

It works fine with BloomRPC. I see the progress. 
But how can I cancel the stream?

My implementation does something like that:
                if (context.CancellationToken.IsCancellationRequested)
                    break;

**Comment by fenos** [comment]
In order to cancel the stream you just need to press the same *STOP* button, it will cancel the stream

**Comment by jankrynauw** [comment]
Will this behaviour be different for TLS and non-TLS connections?  

Pointing BloomRPC to a localhost and pressing STOP cancels the stream.  However, when deploying the exact same code/server to Google Cloud Run, pressing STOP does not seem to cancel the stream.  Apart from localhost vs. Google Cloud Run host, the only difference is that Google Cloud Run requires a TLS connection.
I've asked a [related question on SO](https://stackoverflow.com/questions/66861010/how-to-detect-a-cancelled-lost-closed-connection-in-cloud-run-with-grpc-server-s)

**Comment by jankrynauw** [comment]
Ignore the above - I needed to activate HTTP/2 connections on my Cloud Run deployment.
