### ISSUE TITLE
BloomRPC does not work correct(?) with import

### ISSUE THREAD

**Issue by NUnitTester** [uw-labs/bloomrpc#145]
If ist works, depends where the import is placed.

This works:
syntax = "proto3";
option csharp_namespace = "grpcApp";
package MyTest;
import "google/protobuf/empty.proto";
service Service1 { ... }
service Service2 { ... }

This doesn't work for load by BloomRPC, but seems to be correct, if service1 doesn't need the import. My compiler works fine with it:
syntax = "proto3";
option csharp_namespace = "grpcApp";
package MyTest;
service Service1 { ... }
import "google/protobuf/empty.proto";
service Service2 { ... }

**Comment by fenos** [comment]
You need to use the `import path` functionality in bloomrpc which is the same exact thing of using the `-I` or `--import_path` of the `protoc` compiler

**Comment by NUnitTester** [comment]
Hi Fenos,

have you seen the differenc ebetween the both scripts, the first is working with BloomRPC, the second doesn't? The import pathes are the same in both scripts, so why should specifying an path change anything?

The only thing is, that the import-Command has changed the line because Service1 doesn't need it.
If you were right, the first script won't work in BloomRPC, right? - But it does!
