### ISSUE TITLE
BloomRPC parsing request error 

### ISSUE THREAD

**Issue by pthor11** [uw-labs/bloomrpc#146]
I have a grpc request, which request params would be:

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9***",
  "query": "{"username": "santa"}"
}

This can not be executed because BloomRPC giving error: Expected ', ' instead of 'u'

![Screen Shot 2019-11-27 at 7 45 21 PM](https://user-images.githubusercontent.com/33623944/69724539-b03b0280-114e-11ea-93d7-4c85c764c542.png)

How could I make it right?!

**Comment by fenos** [comment]
that's not valid JSON please use:

```
{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9***",
"query": { "username": "santa"}
}
```
