### ISSUE TITLE
"View Proto" button is broken

### ISSUE THREAD

**Issue by joshfrench** [uw-labs/bloomrpc#148]
Clicking the "View Proto" button begins to slide in a new view, but the UI resets itself before the transition finishes.

![bloom](https://user-images.githubusercontent.com/4573/71028023-70769380-20da-11ea-9b11-3003a8e19b44.gif)

This happens with any proto I try. The recording was made with the following:
```
syntax = "proto3";
package hello;

service HelloWorld {
  rpc SayHello(SayHelloRequest) returns (SayHelloResponse) {}
}

message SayHelloRequest{
  optional string name = 1;
}

message SayHelloResponse {
  optional string value = 1;
}
```

I'm using v1.3.2 built from source on OS X 10.14.6.

**Comment by raymondle** [comment]
Same issue here when clicked ViewProto or Import Path button.

**Comment by fenos** [comment]
What version are you using?
