### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by tracker1** [uw-labs/bloomrpc#15]
FYI, should be able to get a free Azure DevOps (formerly VSTS, Visual Studio Team Services) that includes one Windows agent on Azure that should have enough time.  It also supports GitHub webhooks, depending on your CI/CD process.

I'm not an MS guy so much, but do like to see things in the big 3 platforms as much as possible.

**Comment by fenos** [comment]
Amazing thanks! I’ll give it a go!

**Comment by fenos** [comment]
Now that BloomRPC runs on TravisCI we might be able to use it to build the windows installer too! That would be amazing! Here is where I read about it: https://blog.travis-ci.com/2018-10-11-windows-early-release

I'll give it a try this evening so hopefully, we'll have windows support very soon!

**Comment by julianah** [comment]
I've built a windows release  by:
```
 npm install --global --production windows-build-tools
npm config set msvs_version 2017
```
cd into bloomrpc folder 
yarn install
./node_modules/.bin/electron-rebuild
 npm run package-win
```
The executables are under the `bloomrpc\release\` folder

**Comment by pzduniak** [comment]
That's weird, I get an empty white screen when I run my build. Any ideas on how to debug it?

**Comment by fenos** [comment]
@pzduniak that it's likely to happen when `grpc` couldn't compile successfully for your OS. 
Grpc node uses the native binary which needs to be compiled during the electron build.

when running the command `./node_modules/.bin/electron-rebuild` that should will rebuild the binary for the electron + OS environment you are on.

If you followed @julianah steps that should work. What OS version are you running on?

**Comment by pzduniak** [comment]
I did in fact follow all the steps, that's why I'm confused. I can't run it in dev mode either, webpack hmd (I think that was the name) endpoint never responds to the HTTP request. No logs are anywhere to be found, everything else behaves as expected.

**Comment by fenos** [comment]
@pzduniak Hi!

Try to run the dev mode with the following commands one more time.
We should find out from the chrome console log what's the error you are getting:

**Setup:**
```
rm -rf ./node_modules
yarn install
./node_modules/.bin/electron-rebuild
```

**Run:**
```
npm run hot-server

// in another terminal once the hot-server finishes

npm run start-hot
```

It should open the application with chrome inspector open, go to console and see what's the error you are getting and paste it here.

**Comment by fenos** [comment]
closed by https://github.com/uw-labs/bloomrpc/pull/49

**Comment by pzduniak** [comment]
Thank you so much guys, everything works here now!

**Comment by djensen47** [comment]
Would it  be possible to get the Windows build instructions in the README. It's not a huge deal but to get the build working I had to dig into closed issues and run @julianah's instructions.
