### ISSUE TITLE
UX: path configuration

### ISSUE THREAD

**Issue by smnbbrv** [uw-labs/bloomrpc#165]
Hi guys,

your tool is great and helps a lot! Thank you!

We had a similar to this https://github.com/uw-labs/bloomrpc/issues/132 issue and could not find out why nothing we do works, until we started debugging the tool in dev mode and found out that the path we set up is not reaching the proto loader.

Apparently we thought when we select the path directory from the file browser we expected that it is automatically added and the "+" button is there to add another path.

This costed me and my colleague a couple of hours.

Now I know how to deal with this, but for the new users this might be very frustrating...

And now to the possible solution: 

```
[input with path to write] [+button]
or select directory [file browser button, add on select]
```

This way it will be clear to everybody.

**Comment by fenos** [comment]
@smnbbrv thank you very much for your constructive feedback. 
I'm you had to spend sometime figuring out the import paths button, i'll be happy to automatically add the path once you select it from the browse window.

I will also keep the + button if someone wants to enter it manually 👍

**Comment by sjaramillo-pa** [comment]
You’re sending these emails to the wrong person I am not in business with you

Sent from my iPhone

On Jan 27, 2020, at 3:27 AM, Fabrizio <notifications@github.com> wrote:

﻿

@smnbbrv<https://github.com/smnbbrv> thank you very much for your constructive feedback.
I'm you had to spend sometime figuring out the import paths button, i'll be happy to automatically add the path once you select it from the browse window.

I will also keep the + button if someone wants to enter it manually 👍

**Comment by fenos** [comment]
@sjaramillo-pa you are getting those emails because you are watching the project.
If you don't want to get them just ticket the option **Releases Only** .
i'm not in business with you too 😄 

![Screenshot 2020-01-27 at 13 17 15](https://user-images.githubusercontent.com/4754064/73177617-5d0e0d80-4107-11ea-8c3f-41612b53251a.png)
