### ISSUE TITLE
App Icon does not appear in app switcher (Arch Linux Gnome-Shell)

### ISSUE THREAD

**Issue by glutamatt** [uw-labs/bloomrpc#170]
version `bloomrpc 1.4.1-1` via https://aur.archlinux.org/packages/bloomrpc/ 

[.desktop file](https://aur.archlinux.org/cgit/aur.git/commit/bloomrpc.desktop?h=bloomrpc&id=a4ab43119b05698203a679036a4ce656cafd5fbf)

### window overview and icon bar

![image](https://user-images.githubusercontent.com/1442992/73545322-65ce4e80-443b-11ea-930f-dca55f433380.png)

### app switcher

![image](https://user-images.githubusercontent.com/1442992/73545393-90b8a280-443b-11ea-9f4d-6353106222c0.png)

> The icon displayed somewhere :

![image](https://user-images.githubusercontent.com/1442992/73545535-c78eb880-443b-11ea-8f01-4e0095fbb8cd.png)

![image](https://user-images.githubusercontent.com/1442992/73545679-176d7f80-443c-11ea-8010-c2682aac1d6d.png)

**Comment by deitrix** [comment]
I had a similar issue on Ubuntu 18.10.

![image](https://user-images.githubusercontent.com/14089691/73936710-563b8380-48db-11ea-9d6a-bc19fb786561.png)

I managed to get it working by following the accepted answer in this forum: [Icon missing when application is launched](https://askubuntu.com/questions/558098/icon-missing-when-application-is-launched)

It was just a case of changing `StartupWMClass` in `/usr/share/applications/bloomrpc.desktop` from `BloomRPC` to `bloom-rpc-client`:

```
[Desktop Entry]
Name=BloomRPC
Comment=GRPC GUI client
Exec="/opt/BloomRPC/bloomrpc" %U
Terminal=false
Type=Application
Icon=bloomrpc
StartupWMClass=bloom-rpc-client
Categories=Development;
```

**Comment by denislobanov** [comment]
I don't use a WM that supports icons; @glutamatt if you could try adding `StartupWMClass=bloom-rpc-client` to your `/usr/share/applications/bloomrpc.desktop` to test if this would work on arch?

I'll push an updated PKGBUILD if this works.

**Comment by glutamatt** [comment]
@denislobanov 🏆
i'll try to find out how to update https://aur.archlinux.org/cgit/aur.git/tree/bloomrpc.desktop?h=bloomrpc
thanks bro

**Comment by denislobanov** [comment]
just `sudo vim` the path in your system and see if it makes a difference. You don't have to rebuild the whole package.

**Comment by denislobanov** [comment]
Though if you're curious on how to modify the pkgbuild, then update the .desktop file, sha1sum & update the hash in the pkgbuild

**Comment by glutamatt** [comment]
sure it's fine on my laptop, i was talking about the versioned file in aur git package
https://aur.archlinux.org/cgit/aur.git/commit/bloomrpc.desktop?h=bloomrpc&id=a4ab43119b05698203a679036a4ce656cafd5fbf

**Comment by glutamatt** [comment]
https://aur.archlinux.org/packages/bloomrpc/#comment-728039 seems already patched  🏎️

**Comment by denislobanov** [comment]
Im the maintainer of the AUR package ;)
