### ISSUE TITLE
Cannot import another protobuf file

### ISSUE THREAD

**Issue by zaka634** [uw-labs/bloomrpc#179]
I define a protobuf object file for the data model in a file, then use the service.proto to import that data model protobuf. When I imported the service.proto, I got the exception : Error while importing protos.

**Comment by fenos** [comment]
Can you share the protofile, otherwise i cannot help you

**Comment by deitrix** [comment]
Make sure you have your protoc import paths defined in Bloom.

![image](https://user-images.githubusercontent.com/14089691/74931697-147d0380-53d8-11ea-8c17-909db468c346.png)

![image](https://user-images.githubusercontent.com/14089691/74931389-6709f000-53d7-11ea-8b5c-75fbbf53e4b3.png)

**Comment by zaka634** [comment]
Thanks for the reply, specify the path works. @fenos , sorry I was out of Internet for the past couple days.
