### ISSUE TITLE
Add bloomrpc to flathub?

### ISSUE THREAD

**Issue by Arxcis** [uw-labs/bloomrpc#183]
I would love to be able to do 
```
flatpak install bloomrpc
```
All we would need to do is create a pull request here, https://github.com/flathub/flathub with a setup file.
Is this of interest to the developers of this app?
I could help, if we need to figure something out or discuss about flatpak/flathub.

Here are some developer documentation for electron on flatpak https://docs.flatpak.org/en/latest/electron.html

**Comment by fenos** [comment]
@Arxcis Hello!

I'm absolutely interested on supporting  `flatpak` at the condition that you or someone else will be happy to maintain the setup file as new version of bloomrpc come out

**Comment by Arxcis** [comment]
@fenos Thank you for being open to this idea. I have never done an actual PR to flathub yet, but I have 4 years of full-time experience with developing software on github, so I think I will be able to pull it off if I try. 

My first step will be to package and build `bloomRPC` with Flatpak locally. I'll post updates here on my progress.

**Comment by Arxcis** [comment]
@fenos As far as I can tell the only system dependencies for building and running are `yarn` and `node/npm`. Am I correct? Do you support a specific version of node/yarn or do you just stick to the latest version at any given time?

**Comment by Arxcis** [comment]
The question above may be irrelevant. I am currently trying out `Bitwardens` approach found here https://github.com/flathub/com.bitwarden.desktop/blob/master/com.bitwarden.desktop.yaml

They just pull down the `.deb` package, unpack and run it. Promising...

**Comment by Arxcis** [comment]
So a little update. Of course deploying to Flathub was harder than expected, as expected :v 

I ran into a few issues with the `flatpak/flatpak-builder-tools`: 
- https://github.com/flatpak/flatpak-builder-tools/issues/101
- https://github.com/flatpak/flatpak-builder-tools/issues/103.

The flatpak-community has been helpful so far, so I am optimistic.
The open PR can be found here https://github.com/flathub/flathub/pull/1406.

**Comment by jackielii** [comment]
super, thanks for the contribution
