### ISSUE TITLE
BloomRPC - 14 UNAVAILABLE: failed to connect to all addresses

### ISSUE THREAD

**Issue by rizi** [uw-labs/bloomrpc#185]
![BloomRPC](https://user-images.githubusercontent.com/796258/75326176-71fecd80-587a-11ea-8321-d7ec2f306e35.png)
![TLS_Issue](https://user-images.githubusercontent.com/796258/75328559-80e77f00-587e-11ea-930b-709356b4a836.png)

I have a .net core 3.1 grpc service with two methods, calling the methods from the c# client does work well.

btw. I use the server certificate that has been generated by .net core.

I'm using the latest BloomRPC version (1.4.1) and I tried localhost:5001, 127.0.0.1:5001 and 0.0.0.0:5001 with no luck.

Using BloomRPC causes the following error (displayed in BloomRPC: Repsonse {
  "error": "14 UNAVAILABLE: failed to connect to all addresses"
}

On the gRPC server side I got the following exception:
"Authentication failed because the remote party has closed the transport stream."

I'm using Win10 Enterprise, can you help me to figure out the problem?
br

**Comment by cafegee** [comment]
I had similar problem as yours, I figured out it was a problem with the ssl certificate configured in the krestrel server, I ended up using just to expose http on the grpc service, and get bloomRPC working with the server. Will figure out the problem with ssl later.

To configure GRPC .net core using http , you can add following code.

.ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseKestrel(options =>
                {
                    options.ListenLocalhost(9046, o => o.Protocols = HttpProtocols.Http2);                  
                });

On bloomRPC, just use root certificate, and using 0.0.0.0:9046 as your address.

Hope this helps.

**Comment by rizi** [comment]
@cafegee thx for the hint.
It's working for me as well, can you give me a little bit more info:

why does kestrel know that 9046 it's not an https port and 5001 is one? (some sort of convention?)

Why do I have to choose "root certificate" on bloomRPC? if kestrel does not use https at all?
What is the "root certificate? where can I find it on my windows machine?

What's also very interesting is, that if I don't change the port as you suggested an open https://localhost:5001 in chrome/firefox the certificate is shown as "correct"/trusted.

AND using this tool to call my grpc service with the default configuration (https and port 5001) does work without any issues? (https://github.com/fullstorydev/grpcui)

I don't want to blame bloomRPC, I just want to understand what's going on.

br

**Comment by rizi** [comment]
Any update/help would be highly appreciated

**Comment by Hotkey** [comment]
@rizi i agree with you ;) Any update ?

**Comment by Hotkey** [comment]
@rizi It worked, I think it's really a ssl cert problem. I changed port to 9046 without https. For instance on my local like that "localhost:9046"

**Comment by rizi** [comment]
@Hotkey I think it depends which technology you are using.
If I use .net core as grpc server then bloomRPC it's not working (neither with the developer certificate created by .net core nor with a self signed certificate.

BUT if I use the full framework (.net 4.7.x or. net 4.8.x) bloomRPC it's working with the certificate created by .net core and with the self signed certificate, so I think bloomRPC have to do "something additional" to satisfy .net core (maybe send the whole certificate chain and not only the server certificate or something like that).

This seems to confirm my thesis: https://stackoverflow.com/questions/58125102/grpc-net-client-fails-to-connect-to-server-with-ssl

**Comment by Hotkey** [comment]
@rizi  Actually i'm running on .net core 3.1 and now working perfectly

**Comment by rizi** [comment]
> @rizi Actually i'm running on .net core 3.1 and now working perfectly

Does it work with http or does it also work with https? If it's now working with https as well I'm curious what to do. Br

**Comment by Hotkey** [comment]
@rizi You are right, it's always failed with https. Only works with http. I tried with openssl (generated for localhost) and I also separated key and cert files for ui uploading but it didn't work ;-)

**Comment by Hotkey** [comment]
Screenshot

<img width="972" alt="local_ssl" src="https://user-images.githubusercontent.com/1449423/83734882-41d48100-a658-11ea-9fd9-76e876446927.PNG">

**Comment by Hotkey** [comment]
Hi @rizi, i blogged this issue and i solved that problem with using the default iis cert

https://medium.com/@farukalkaya/bloomrpc-missed-gprc-gui-client-9f464c4f3d63?sk=7976d232e12fe183a6ea0c5fd880376f

**Comment by rizi** [comment]
> Hi @rizi, i blogged this issue and i solved that problem with using the default iis cert
> 
> https://medium.com/@farukalkaya/bloomrpc-missed-gprc-gui-client-9f464c4f3d63?sk=7976d232e12fe183a6ea0c5fd880376f

Thx!

**Comment by jackielii** [comment]
I believe this is resolved?

**Comment by goyalneeraj18** [comment]
is this still a problem some times? I am facing this with BloomRPC 1.5.3

**Comment by deathchurch** [comment]
I am not able to get this to work even with following the suggested workaround, using the latest version of BloomRPC

**Comment by sgc109** [comment]
I'm facing this too with BloomRPC 1.5.3
