### ISSUE TITLE
Unknown enumeration values appear as default values

### ISSUE THREAD

**Issue by zaininfo** [uw-labs/bloomrpc#186]
**What happens?**
When a request containing a repeated enumeration field is sent with an unknown value in that field, the server receives the request with that field containing the default value of the enumeration.
**Protobuf (v3):**
```proto
message Request {
	repeated SomeEnum some_enums = 1;
}

enum SomeEnum {
	DEFAULT_ENUM_VALUE = 0;
}
```
**Request (in BloomRPC):**
```json
{
  "some_enums": [
    1
  ]
}
```
**Response (in Go):**
```Go
someEnums := req.GetSomeEnums()
// where someEnums is:
// []protobuf.SomeEnum{
// 	   protobuf.SomeEnum_DEFAULT_ENUM_VALUE
// }
```
**Further context:**
As per my understanding the reason could be that [JavaScript protobuf specifications](https://developers.google.com/protocol-buffers/docs/reference/javascript-generated#enum) allow unknown enumeration values:
>Note that in proto3, you can set an enum field to any value.

While, afaik, Go protobuf specifications don't allow that.

**Comment by jackielii** [comment]
this is probably expected behaviour:

1. integer is looked up when encoding the message 
2. no matching enum found, default value is sent
3. server sees default value
