### ISSUE TITLE
The "Send" icon is rendered on top of request payload

### ISSUE THREAD

**Issue by nomaed** [uw-labs/bloomrpc#189]
This is a UX issue mostly. The green arrow (Send) icon is rendered between the editor (request payload) and the response, but if the request contains a long line, the icon overlaps it and makes it difficult to work with the line of code.

This is kind of an edge case (the long line need to be located exactly in the middle of the editor), bit it can be very annoying in a case that there wasn't anywhere to scroll up or down.
While the fact that the content it slightly obscured is not such a big deal, when one needs to click inside the editor panel to edit the value (for example if I want to mark the entire content of the string between the quotes, in my example), then it actually blocks the ability to do so.

<img width="680" alt="Screen Shot 2020-03-07 at 12 16 37" src="https://user-images.githubusercontent.com/9551921/76141550-287a6380-606e-11ea-9825-f5b1a6ae722b.png">

I can't think of a better solution than to add some padding to the editor's right.

That's on macOS 10.15.3

**Comment by jackielii** [comment]
this is a bit annoying, but can be worked around easily by copying the text out to see
