### ISSUE TITLE
Error parsing the request message: map with non-scalar value

### ISSUE THREAD

**Issue by cmagnuson** [uw-labs/bloomrpc#19]
Testing today with the latest release (1.1.1.88) I get this error:

>   "error": "Error parsing the request message, please report the problem sharing the offending protofile"

When loading this proto file:
[https://github.com/cmagnuson/announcerdisplay-protobuf/blob/master/src/main/proto/SettingsMessage.proto](https://github.com/cmagnuson/announcerdisplay-protobuf/blob/master/src/main/proto/SettingsMessage.proto)

It appears the map on line 20 is causing the issue.  If I comment it out or change it to a `map<string, string>` then bloomrpc handles the proto file as expected.

**Comment by fenos** [comment]
Hi thanks for reporting this, 

Yes unfortunately i forgot to cover the map with a non scalar type.
I'll be releasing a fix in a couple of hours

**Comment by fenos** [comment]
@cmagnuson This is now fixed with the patch version `1.1.2` give it a try and let me know how it goes 👍
