### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by donnrri** [uw-labs/bloomrpc#193]
Having followed the instructions provided here 
[https://github.com/uw-labs/bloomrpc/issues/15#issuecomment-448937768](url)

npm install --global --production windows-build-tools
npm config set msvs_version 2017
cd into bloomrpc folder

yarn install
./node_modules/.bin/electron-rebuild
 npm run package-win

I get the following error :
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/electron-v6.1-win32-x64-unknown.tar.gz

This file isn't available.  Can you assist me as I 'd really like to try this aplication.
Thanks for your time.

**Comment by djvickx** [comment]
You can install the Latest Release on Windows by using the executable file provided on the [Release Page](https://github.com/uw-labs/bloomrpc/releases)
