### ISSUE TITLE
proto2 null fields are returned as non-null default values

### ISSUE THREAD

**Issue by vivianliang** [uw-labs/bloomrpc#197]
example proto and corresponding Go struct:
```proto
syntax = "proto2";

message Response {
  optional int32 id = 1;

  enum Status {
    UNKNOWN = 0;
  }
  optional Status status = 2;
}
```
```golang
type Response struct {
  Id *int32
  Status *Response_Status 
}
```

response in Go:
```golang
&Response{
  Id: nil,
  Status: nil,
}
```

response in bloomrpc:
```json
{
  "id": 0,
  "status": "UNKNOWN"
}
```

expected response in bloomrpc:
```json
{
  "id": null,
  "status": null
}
```

**Comment by jackielii** [comment]
I believe this is how protobufjs lib treats it, there is no optional field anymore in proto3, so empty response will just be default value. I think it's better to raise an issue in protobufjs lib
