### ISSUE TITLE
Blank screen after opening and selecting proto files

### ISSUE THREAD

**Issue by torandu** [uw-labs/bloomrpc#2]
The screen goes blank (white screen that only displays the menu options) after opening proto files and randomly selecting the files in the left nav. The error is reproducible. The only way to "recover" seems to be to delete the config directory. Simply closing and re-running the app results in the while/ blank screen.

Reported for Debian (testing) using the v1.0.0 .deb package.

Steps to reproduce:
1. Open bloomrpc
2. Click the plus button to add proto files
3. Select proto files (in my case, I selected 21 files)
4. Click open

The files initially loaded and were displayed in the left nav, However, after randomly selecting files in left nav, the screen went blank/ white. There was no way to recover in the UI. 

Results:
1. Blank screen
2. Only menu options are displayed: File, View, Help
3. Closing and restarting results in blank screen (unrecoverable error)

The error/ problem is reproducible.

**Comment by fenos** [comment]
Thanks for reporting this. 

Is it possible to send me all the profiles you uploaded, there might be some parsing issue on 1 or few of them.

**Comment by fenos** [comment]
I've reproduced the issue, thanks for the descriptive steps.

The issue happens when a protofile has a `bytes` type specified in the Request message.
 
I'll also put some guard on the parsing so the blank screen should never happen again.

I'll release the fix soon

**Comment by simonhdickson** [comment]
I get this exact same issue using the same steps, I will send you the proto file.

**Comment by antegulin** [comment]
How to recover from the blank screen?

**Comment by fenos** [comment]
@antegulin You can recover by deleting the stored data by going to:

Edit > Clear Storage

**Comment by alexandrukis** [comment]
```
cd ~/.config/bloom-rpc-client                                                                                              
rm editor.json
```

**Comment by tp** [comment]
on macOS:

```
rm ~/Library/Application\ Support/bloom-rpc-client/editor.json 
```

**Comment by sarveswaran-m** [comment]
In addition to the step by @tp , I had to do this on macOS to recover:

` rm ~/Library/Application\ Support/bloom-rpc-client/importPaths.json`
