### ISSUE TITLE
Has anybody ever tried calling Firestore using BloomRPC

### ISSUE THREAD

**Issue by dunyakirkali** [uw-labs/bloomrpc#209]
https://stackoverflow.com/questions/62126642/how-to-make-a-call-to-firestore-using-grpc

**Comment by dunyakirkali** [comment]
I did solve the issue. See ☝️

**Comment by RaviH** [comment]
I keep getting this when trying to import firestore.proto. What am I doing wrong?

![image](https://user-images.githubusercontent.com/141136/114462115-79288e00-9b97-11eb-9881-ba5b52431eb2.png)

![image](https://user-images.githubusercontent.com/141136/114462165-8b0a3100-9b97-11eb-9704-c7878205f390.png)

![image](https://user-images.githubusercontent.com/141136/114462030-5a29fc00-9b97-11eb-88af-5bf88da7e46e.png)
