### ISSUE TITLE
Error 14 UNAVAILABLE: Trying to connect an http1.x server

### ISSUE THREAD

**Issue by PS-StuartZahn** [uw-labs/bloomrpc#21]
Test url is sub.domain.com:443 on https

Getting error 

{
  "error": "14 UNAVAILABLE: Trying to connect an http1.x server"
}

**Comment by fenos** [comment]
Hi 👋,

TLS is scheduled on the next release 1.2, it will be out before Christmas 🎄 
You can check #8 for the progress
