### ISSUE TITLE
The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by parin13** [uw-labs/bloomrpc#213]
I am getting this error message when trying to import proto file
![1](https://user-images.githubusercontent.com/12233451/84280532-25a07a80-ab57-11ea-8b5e-02e7956203a0.png)
![2](https://user-images.githubusercontent.com/12233451/84280544-29cc9800-ab57-11ea-9392-6e4f3656ae6e.png)
![3](https://user-images.githubusercontent.com/12233451/84280567-3224d300-ab57-11ea-9aaf-6d28e8222d63.png)

**Comment by jungyu-rim** [comment]
Same problem at Windows 10

**Comment by parin13** [comment]
@jungyu-rim  did you find any solution for this ?

**Comment by jungyu-rim** [comment]
Check #210 

- Solution: delete importPaths.json from cache, (C:\Users<user>\AppData\Roaming\bloom-rpc-client\importPaths.json)

**Comment by jackielii** [comment]
seems resolved?
