### ISSUE TITLE
UNAVAILABLE: Trying to connect an http1.x server

### ISSUE THREAD

**Issue by adefalque** [uw-labs/bloomrpc#220]
I recently started to get this error for any GRPC calls I do from Bloom.
It was working perfectly and suddenly stopped, I guess after some conflicting software installed, or Windows settings changed?

I get the same error on TLS or non TLS calls.

Any idea / clue?
Thanks

**Comment by gb1337** [comment]
I have the same issue. Trying to connect to a Grpc-Web server implemented in .Net Core, using the protobuf-net.Grpc package. It's working fine with the Google/MS package.

**Comment by jackielii** [comment]
the grpc-web would be resolved once #269 is merged, please wait for new release soon
