### ISSUE TITLE
add gui option to use plain text transport

### ISSUE THREAD

**Issue by LeiYangGH** [uw-labs/bloomrpc#221]
Currently there's a TLS configuration button, after clicking a dialog prompt and allow user to select certifications.
But during dev/testing we like use plain text(or insecure) transport instead.
The gui should hava a toggle button(checkbox) to let user choose insecure(plain text)/secure(tls).

Or if i completely misunderstood the gui, please help provide a way to set to insecure, thanks!

**Comment by jackielii** [comment]
plain text is the default behaviour, for TLS, you need to add the server cert to make secure calls
