### ISSUE TITLE
[BUG] BloomRPC refuses to connect if the gRPC endpoint supports both HTTP/1.1 and HTTP/2

### ISSUE THREAD

**Issue by user72356** [uw-labs/bloomrpc#252]
My gRPC endpoint supports both HTTP/1.1 and HTTP/2 as is standard for ASP.NET Core endpoints. It needs to support HTTP/1.1 because regular browser clients and gRPC-Web clients need HTTP/1.1. 

**Expectation:** BloomRPC connects and uses the HTTP/2 protocol to converse with the endpoint.

**Reality:** BloomRPC connects and sees that the endpoint supports HTTP/1.1 and returns an error instead of trying HTTP/2. The error is `"14 UNAVAILABLE: Trying to connect an http1.x server"`

**Workaround:** Create a new HTTP/2 only endpoint on a different port and use that to connect BloomRPC. It would be best to correct the base problem in BloomRPC for sure.

**Comment by jackielii** [comment]
the issue is very suspicious, if your http server supports http1.1 & http2, it definitely needs to to be multiplexed to different routes. for grpc-web feature, we'll release this feature soon. Please watch for the release, will probably do it tonight or tomorrow depending on the building speed

**Comment by ThaDaVos** [comment]
Sorry for commenting on an old and closed issue - but it still exists in BloomRPC - is there any fix in the works?
