### ISSUE TITLE
BloomRPC for Fedora/RHEL/CentOS

### ISSUE THREAD

**Issue by alvarolop** [uw-labs/bloomrpc#255]
Hello,

I would like to know if it is possible to install BloomRPC in this family of Linux distributions. If not, is it expected to be possible in the future?

Best regards,

**Comment by abbottm-go** [comment]
Hi, 

You may be able to build it from source, if you scroll down the readme you should see the install options.

**Comment by alvarolop** [comment]
Hello,

Thank you for your response! I have followed the instructions to "build from source" and this is what I got in the `release` folder:
```
ls -la release/
total 220100
drwxrwxr-x.  3 alvaro alvaro      4096 Oct  5 17:45  .
drwxrwxr-x. 11 alvaro alvaro      4096 Oct  5 17:43  ..
-rw-rw-r--.  1 alvaro alvaro  78059574 Oct  5 17:45  bloomrpc_1.4.1_amd64.deb
-rwxr-xr-x.  1 alvaro alvaro 147288362 Oct  5 17:43 'BloomRPC 1.4.1.AppImage'
-rw-rw-r--.  1 alvaro alvaro       652 Oct  5 17:39  builder-effective-config.yaml
-rw-rw-r--.  1 alvaro alvaro       382 Oct  5 17:45  latest-linux.yml
drwxrwxr-x.  5 alvaro alvaro      4096 Oct  5 17:43  linux-unpacked
```
There is no `.rpm` package. The only option would be to use the .AppImage option? Shouldn't the `build from source` steps create a `.rpm`?

**Comment by jackielii** [comment]
@alvarolop you can use the `.AppImage` which is runnable directly
