### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by cheshir** [uw-labs/bloomrpc#265]
Part of my proto files wasn't showed properly – they've been added to the list of loaded protos but I can't do anything with them. Looks like they don't have methods to call.

How can I find a cause of this? Is there any logs that could be attached to the next issue?

**Comment by komalbhola** [comment]
Facing the same issue. After importing a proto file, nothing happens.

**Comment by jackielii** [comment]
Can you share a minimal reproducible proto file.

You can also try to debug BloomRPC following the instructions from README

**Comment by cheshir** [comment]
@jackielii I can't share with you a minimal reproducible proto file. That's why I asked about debugging methods. Maybe there is some log file or it's possible to open the developer toolbar with some magic key combination.

**Comment by jackielii** [comment]
@cheshir in latest version, you can open the console via "view" -> "open developer tools"
