### ISSUE TITLE
Hotkey to send request does not include body from editor

### ISSUE THREAD

**Issue by op2rules** [uw-labs/bloomrpc#279]
Target: localhost:xxxx

Body: {
  "test": [
    {
      "test": "test",
      "test2": "test2",
      "test3": "test3"
    },
] 
}

When I ust ctrl+enter, it's as though the request body is completely empty!

**Comment by jackielii** [comment]
I know this is a bug in 1.4.1, did you try latest version?

**Comment by op2rules** [comment]
1.4.1 it was! Thanks for the quick reply :)
