### ISSUE TITLE
Big Sur incompatible

### ISSUE THREAD

**Issue by vikihleblya** [uw-labs/bloomrpc#284]
Cannot launch BloomRPC on Mac OS Big Sur.
<img width="698" alt="Screenshot 2020-11-28 at 18 12 56" src="https://user-images.githubusercontent.com/38594728/100518850-5af06180-31a5-11eb-8f7b-a8ba510a057d.png">
Can you help please?
<img width="372" alt="Screenshot 2020-11-28 at 18 11 00" src="https://user-images.githubusercontent.com/38594728/100518821-15cc2f80-31a5-11eb-9931-1946b01fd157.png">

**Comment by vikihleblya** [comment]
Any updates?

**Comment by abhishek-nigam** [comment]
<img width="328" alt="Screenshot 2020-12-21 at 3 12 27 PM" src="https://user-images.githubusercontent.com/21065165/102762908-f3da5d00-439e-11eb-9af7-efaea004e7e8.png">
macOS Big Sur 11.0.1 doesn't allow to open the app. Tried Homebrew and DMG installation. Earlier, we could go to applications menu in Finder, right-clicking on BloomRPC listing, and then clicking open... it would open. But now it gives this message.

**Comment by nWacky** [comment]
I managed to resolve the issues by downloading and installing `BloomRPC-1.5.2.dmg`. I had to open the app, then verify it in Settings -> Security. After that it was working fine for me.

`bloomrpc-1.5.2-mac.zip` had a 'File too short' issue with the Electron Framework

**Comment by vikihleblya** [comment]
@nWacky, thanks a lot!

**Comment by hartmut-co-uk** [comment]
I've had a similar issue, I first had downloaded `BloomRPC-1.5.2-mac.zip` which wasn't working with (identical to initial post's screenshot).
The .dmg is working fine.
