### ISSUE TITLE
OpenAPI Annotation causes BloomRPC to fail loading proto

### ISSUE THREAD

**Issue by AntoineToussaint** [uw-labs/bloomrpc#286]
First, thank you for the awesome work!

I have a proto file that contains OpenAPI annotations:

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) {

}..

at the top level but that makes bloomrpc very unhappy:

```
Error while importing protos
illegal token 'option' ...
```

Is there a work around?

**Comment by jackielii** [comment]
can you provide minimum reproducible proto file?

I suspect the issue might be in the protobufjs lib, which we use to parse proto files

**Comment by AntoineToussaint** [comment]
```proto

syntax = "proto3";


package helloworld;


import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "helloworld";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
	info: {
		title: "Hello World";
		version: "1.0";
    };
};

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
```

**Comment by EricSmekens** [comment]
I've tried this with the latest version of protobuf, 6.10.2, but indeed, the dependancy is within the bloomrpc-mock package.
I've seen you already made a pull-request, so I'm linking it here.

https://github.com/uw-labs/bloomrpc-mock/pull/14

**Comment by AntoineToussaint** [comment]
Works on latest version so closing.
