### ISSUE TITLE
No external IPs accepted

### ISSUE THREAD

**Issue by Ka0o0** [uw-labs/bloomrpc#292]
Hi,
I'm trying to debug a GRPC application which works perfectly if my GRPC service is running locally. As soon as I put the GRPC service into a Kubernetes cluster and try to connect to the GRPC service via its public IP address, BloomRPC does not connect anymore. The error is `"error": "14 UNAVAILABLE: failed to connect to all addresses"`

I tried to debug it with Wireshark and I cannot even see any TCP requests going out to the server from BloomRPC which seems kinda odd. I can connect to the GRPC service port via ncat which lets me think that my firewall settings are correct.

Any suggestions? I'm running it on Fedora33

**Comment by Ka0o0** [comment]
I turns out that my proxy settings were causing the problem. Closing this.

**Comment by mrjosh** [comment]
can you inform me how did you solve this?
my problem is, i cant connect to my grpc service without giving the BloomRPC the custom certificate
The grpc service is also on a k8s cluster
Im using nginx ingress controller
