### ISSUE TITLE
Support for Authorization Headers

### ISSUE THREAD

**Issue by dotpyfe** [uw-labs/bloomrpc#31]
would be nice to be able to add an authorization header

**Comment by fenos** [comment]
Hi @dotpyfe,

The client already supports "headers", I suppose that is achieved with metadata

<img width="1080" alt="screenshot 2019-01-04 at 20 41 45" src="https://user-images.githubusercontent.com/4754064/50709875-2cbd8200-1061-11e9-9164-68066a270dff.png">


Will this be enough for supporting the Authorization header?

**Comment by dotpyfe** [comment]
oh gotcha, i missed that section! 

thanks a ton for the speedy reply, might be good to include that in the docs somewhere, i wasn't able to find anything looking through the repo.

thanks again!

**Comment by fenos** [comment]
No worries! 

You are right, I'll need to write some documentation one of those days 👍

**Comment by Webonaute** [comment]
How you define contract to see this header in bloomrpc?
```
{
    "Authorization": "Bearer  token"
}
```
