### ISSUE TITLE
Illegal id -1 for reserved -1;

### ISSUE THREAD

**Issue by VivekRagunathan** [uw-labs/bloomrpc#35]
Getting the following error for a proto file with `reserved -1`.

```
Error while importing protos illegal id '-1' 
```

**my.proto**

```
syntax = "proto3";

....

message Status {
  enum Values {
    reserved -1;
    INVALID = 0;
    OK = 1;
    OK_BUT_WARNINGS = 2;
    ...
  }
}

....
```

**Comment by fenos** [comment]
Thanks for reporting this issue.

As a first impression it seems that the protobuf.js parser doesn't support the `reserved` keyword.

I'll investigate more, then i'll get back to you

**Comment by fenos** [comment]
@VivekRagunathan The use of **negative** numbers within the `reserved` keyword of `Enums` type is not currently support by the `protobuf.js` parser.

I've raised a PR to them which fixes this issue.
