### ISSUE TITLE
Protobuf Extensions Support

### ISSUE THREAD

**Issue by yeenow123** [uw-labs/bloomrpc#36]
This is more of a question rather than issue.  Is it planned or even possible to support protobuf extensions?

**Comment by kparlar** [comment]
I have got exception for the same problem i believe
![image](https://user-images.githubusercontent.com/15136174/51438706-ed717100-1caf-11e9-987e-b5a0414d27b9.png)

**Comment by fenos** [comment]
Hi,

This is something that I need to verify, given that the parsing logic is all done by the `protobuf.js` I'm not sure if they allow for different extension. Will dig into this and come back here

**Comment by bjaglin** [comment]
We also bitten by this. It does look like `protobuf.js` supports it: https://github.com/dcodeIO/protobuf.js/blob/e8449c4bf1269a2cc423708db6f0b47a383d33f0/tests/comp_options-textformat.js

I am getting an error when importing something even more simple that their test case in BloomRPC:
```proto
syntax = "proto3";

import "google/protobuf/descriptor.proto";

extend google.protobuf.FieldOptions {
  string description = 50000;
}
```

I'll see if I can run BloomRPC from the sources to investigate.

**Comment by bjaglin** [comment]
It looks like something explicit is needed https://github.com/dcodeIO/protobuf.js/blob/d6e3b9e/src/common.js#L36
