### ISSUE TITLE
build instructions for MacOS

### ISSUE THREAD

**Issue by mscurtescu** [uw-labs/bloomrpc#38]
Please add build instructions for MacOS as well. What package should be used? package-linux?

**Comment by fenos** [comment]
Hi, I'll need to revamp the README file soon. Thanks for the feedback.

This is the command to build on mac (`npm run package`):
https://github.com/uw-labs/bloomrpc/blob/master/package.json#L20

**Comment by fenos** [comment]
Closing this, the README is now giving the right instructions for building from source
