### ISSUE TITLE
Importing Protos doesn't work

### ISSUE THREAD

**Issue by asad-awadia** [uw-labs/bloomrpc#39]
<img width="497" alt="screen shot 2019-01-25 at 3 17 52 pm" src="https://user-images.githubusercontent.com/6923282/51770640-7293c600-20b4-11e9-84d1-f498f7d6164f.png">

Importing any proto file causes this on version 1.2.1 on Mac [https://github.com/uw-labs/bloomrpc/releases/download/v1.2.1/bloomrpc-1.2.1-mac.zip]

**Comment by fenos** [comment]
Hi can you share an example proto that cause that error please

**Comment by fenos** [comment]
Closed for inactivity

**Comment by xbitres** [comment]
I have the same problem on mac.

Although I cannot share due to confidentiality, I can say that the file has 23Kb.

I think this is a very important problem has to this limitation forbid us from using this in an enterprise environment.

**Comment by asad-awadia** [comment]
@fenos my thing was just a basic echo server if I remember correctly

too much effort to set up not worth it
