### ISSUE TITLE
Importing protos doesn't work if there are cross-file dependencies in the proto files

### ISSUE THREAD

**Issue by shikev** [uw-labs/bloomrpc#40]
For example, if I import a file called `bookshelf.proto` which has the following line `import "protos/api/book.proto";`, the import will fail, stating that an error like `no such Type or Enum 'Book' in Type...`

**Comment by fenos** [comment]
@shikev Hi,

This should definitely work, only if the import is relative to the proto you are loading.

example: if you are trying to load  `$HOME/project/bookshelf.proto` the imports needs to be located in
`$HOME/protject/protos/api`

alternatively, if the path is not relative to the protofile, you can use `import paths` functionality. Imagine your `book.proto` is located in `$HOME/common/protos/api/book.proto`
you can add as an **import path** -  `$HOME/common`. 

Here is some reference images https://github.com/uw-labs/bloomrpc/pull/27

**Comment by shikev** [comment]
Changing it relative imports fixed it, thanks
