### ISSUE TITLE
Response Time

### ISSUE THREAD

**Issue by mfuentesg** [uw-labs/bloomrpc#42]
Hey, thanks for this awesome tool.
It would be great if you can add in some part the response time of any service method.

Thanks!

**Comment by fenos** [comment]
Lovely request! Sure I'd love to see this as well!

**Comment by vctrferreira** [comment]
It's will be implemented? I think that it's one essential feature and needs to be done asap.

**Comment by vctrferreira** [comment]
@fenos if anyone not still working in this feature maybe I can be a contributor with that, what you think about that?

**Comment by fenos** [comment]
@vctrferreira Hi, 
sorry but i've missed your message, i've implemented the feature from you requested, 

I'm really glad for any other contributions given to the project, don't hesitate to open PR's in the future!
