### ISSUE TITLE
Save response in file.

### ISSUE THREAD

**Issue by Zaazik** [uw-labs/bloomrpc#43]
Hello.
How i can save stream response in one large file? When u have many little page Stream 1, Stream 2 Stream N. I need find some data from response by id or by field name and check empty its or now.
If i will save all text response in one large file. I will have chance search in file =) 
I'm apologize for my bad eng.
And thank you very much for the good application.

**Comment by fenos** [comment]
Hi @Zaazik this is a great request! Stay tuned i'll be adding this feature. 
In the mean time you have to do it manually i'm afraid.
