### ISSUE TITLE
Load proto file from HTTP

### ISSUE THREAD

**Issue by eric-taix-teads** [uw-labs/bloomrpc#45]
Instead of loading a proto definition from file, it could be really awesome to load it from a HTTP url.
This is especially helpful when this proto definition comes from a production / test server because it is always up-to-date

**Comment by fenos** [comment]
Agree, this could be a nice functionality to have

**Comment by eric-taix-teads** [comment]
I have started to code it this night. Will send a WIP pull-request then you will be able to start reviewing / commenting my PR
