### ISSUE TITLE
Expose version on linux

### ISSUE THREAD

**Issue by torandu** [uw-labs/bloomrpc#59]
Release version is not exposed in the UI on linux.

Ideally, both the UI and the binary would expose version, e.g. `bloomrpc --version`.

The workaround is to check dpkg status: `dpkg -s bloomrpc | grep Version`

Reported for latest release: 1.2.1-38

**Comment by fenos** [comment]
I don't have a linux machine available to develop on at the moment, any help would be great

**Comment by fenos** [comment]
This is fixed by #77
