### ISSUE TITLE
Blank screen when RPC is renamed.

### ISSUE THREAD

**Issue by electron0zero** [uw-labs/bloomrpc#62]
## Steps to reprodue this issue
1. create a proto file
2. load it in bloomrpc
3. play around/query a RPC
4. rename currently selected RPC 
5. hit reload on bloomrpc
6. :boom: Blank Screen.

## Workaround.
1. go to bloomrpc config dir
	- on linux, it's at `~/.config/bloom-rpc-client`
2. remove `editor.json`
	- NOTE: you will lose all request data(from editor)
3. profit :moneybag:

**Comment by fenos** [comment]
Thanks for reporting this, the fix will be included in the release 1.3 which will be out this week

**Comment by fenos** [comment]
@electron0zero this is now fixed

**Comment by electron0zero** [comment]
@fenos Thanks
