### ISSUE TITLE
Streaming Response Handling

### ISSUE THREAD

**Issue by maarek** [uw-labs/bloomrpc#63]
It would be great to have streaming response tile or append to a larger log of responses. My server moves through responses so quickly that I never see the errors or responses that come through until the last one hits.

**Comment by fenos** [comment]
Hi @maarek , thanks for the feedback!

Did you tried to use the **Interactive** mode? There should be a switch on the top right which will allows you to persist the stream in each tab. Let me know if that helps, probably i should activate that mode by default on stream responses

**Comment by maarek** [comment]
@fenos Actually, I'm not sure if this was my bad or what was up. I never saw those tabs come up before. I was having this issue where locally, even though I told the stream to error (ok or otherwise) in my golang server, it was not terminating the stream in BloomRPC. I didn't dig deep into it and have broke my application since, so I can't test again. But I did have it up in the cloud to play with and it terminates properly and I see those Stream tabs now. 👍 You can probably close this.

**Comment by fenos** [comment]
@maarek Cool let me know if you find any issue, i'll be happy to help. For now let's close this.
