### ISSUE TITLE
Support recursive data structures

### ISSUE THREAD

**Issue by hagen93** [uw-labs/bloomrpc#69]
Trying to load a protobuf with a recursive data structure in it results in the client displaying the message `{"error": "Error parsing the request message, please report the problem sharing the offending protofile"}`. As a minimum viable example of this behaviour, try to load the following protobuf file:

```
syntax = "proto3";

service Main {
    rpc Rpc(Message) returns (Message);
}

message Message {
    Message message = 1;
}
```

**Comment by hagen93** [comment]
I might add that this limitation only seems to affect the pregenerated JSON that fills the screen when you select an RPC to call, and does not stop one from performing the actual RPC call as long as the data is replaced with something valid. I suppose the best fix would be to just generate one level of data when a recursive structure is encountered, and fill the second layer with nulls, or something like that? :)

**Comment by fenos** [comment]
@hagen93 Thanks for reporting the issue.
I totally agree this should be fixed by generating only 1 level of data

I will look after this ASAP 🍻

**Comment by nmartinpunchh** [comment]
I'm having the same issue but with a little more complex data structure

``` protobuf

message Workflow {
  Statement root = 1;
}

message Statement {
  ActivityInvocation activity_invocation = 1;
  Sequence sequence = 2;
  Parallel parallel = 3;
}

message Sequence {
  repeated Statement statements = 1;
}

// Parallel ...
message Parallel {
  repeated Statement statements = 1;
}

message ActivityInvocation {
  string name = 1;
  repeated string arguments = 2;
  string result = 3;
}
```
