### ISSUE TITLE
Blank screen after clicking on service that does not exists

### ISSUE THREAD

**Issue by Zexuz** [uw-labs/bloomrpc#71]
## Problem
When a Rpc Service has the same name as a MessageType in a different package, but is using it via imports, the client will display two different services.  

And when clicking on the second service (The one that does not exist in that package name, nor should it), bloom will display a white page.

![image](https://user-images.githubusercontent.com/12451322/56080380-c20aa800-5e00-11e9-901f-789be9c9ac6c.png)

**Before**
![image](https://user-images.githubusercontent.com/12451322/56080467-e915a980-5e01-11e9-904a-51477d8a2933.png)

**After**
![image](https://user-images.githubusercontent.com/12451322/56080551-b7511280-5e02-11e9-9ebc-545e1bd6533a.png)

## Info
Version: 1.3.0
OS: Windows

## Current Workaround
Go to `...AppData\Roaming\bloom-rpc-client\editor.json` and change the `tabs.activeKey` to a valid key.

### Imported paths
`C:\Users\desktop\Desktop\somePath`

### Proto Files

**C:\Users\desktop\Desktop\somePath\proto\example-messages.proto** 
```proto
syntax = "proto3";

package mypackage.common;

message Example {
}
```

**C:\Users\desktop\Desktop\somePath\proto\service.proto**
```proto
syntax = "proto3";

import "proto/example-messages.proto";

package mypackage.service;

service Example {
    rpc DoSomeThing (DoSomeThingRequest) returns (DoSomeThingResponse) {
    }
}

message DoSomeThingRequest {
}
message DoSomeThingResponse {
    mypackage.common.Example msg = 1;
}
```

Add the `proto\service.proto` and press on the second service.

**Comment by Zexuz** [comment]
I might look in to this myself later, but if anyone has any ideas that would help.

**Comment by fenos** [comment]
@Zexuz Thanks a lot for reporting the issue, your description it's very precise it helps a lot!

I'll be looking at it sometime today, and comeback to you 👍

**Comment by Zexuz** [comment]
No worries, I'm a developer that uses this tool every day when I'm working. And it has made my life so much easier. Just glad I could provide and give something back to make it more awesome! ✌

PS. If you have any ideas of where to look, I would be happy to take another look at it.

**Comment by fenos** [comment]
@Zexuz Hi, 

I spent a little bit of time on this, and i could narrow down the issue.

The problem is happening on this [Line](https://github.com/uw-labs/bloomrpc/blob/master/app/behaviour/protoInfo.ts#L21), it's essentially try to locate the service by this key `mypackage.common.Example` but unable todo so. 

It should traverse the protobuf `Root` object and retrieve the `Service` from it using that full path key as any other protofile is able todo so.

I'm not entirely sure why it cannot locate it with the full path, probably is related to the fact that lives in a different file perhaps? 

i've quickly tried to use the service name only just `Example` instead of `mypackage.common.Example` and it seemed to work just fine as well as other protos.

The code will result as following:

```ts
serviceDef() {
    const serviceName = this.service.serviceName.split('.').pop();

    if (!serviceName) {
       throw new Error(`Cannot locate service name in ${this.service.serviceName}`);
    }
    return this.service.proto.root.lookupService(serviceName);
  }
```

although i'd like todo some more testing with other protobuf files before considering a safe change.

**Comment by Zexuz** [comment]
> The problem is happening on this Line, it's essentially try to locate the service by this key `mypackage.common.Example` but unable to do so.

Isn't the problem that it try to look up the service with key `mypackage.common.Example` in the first place? 

`mypackage.common.Example` does not contain a service, `mypackage.service.Example` contains the service.

**Comment by fenos** [comment]
@Zexuz I see, good point! That's surely the problem. 👍 

i'll have another go to see if I can make it generate correctly, you are also welcome to look this yourself.

### Some Guidance 
- The name is generated by this [Method](https://github.com/uw-labs/bloomrpc/blob/master/app/behaviour/importProtos.ts#L86) and points to the **bloomrpc-mock** library which the editor is using.

- The implementation of `walkServices` can be found [HERE](https://github.com/uw-labs/bloomrpc-mock/blob/master/src/protobuf.ts#L83)

- The bug should be located  [around those lines](https://github.com/uw-labs/bloomrpc-mock/blob/master/src/protobuf.ts#L92-L99)

**Comment by fenos** [comment]
to run `bloomrpc-mock` server you can execute the script inside `bin/` as following:

```
./bin/run C:\Users\desktop\Desktop\somePath\proto\service.proto
```

This should give you instant feedback

**Comment by fenos** [comment]
@Zexuz Doing some progress with this, being a bit busy lately at work but I'm getting to a fix

**Comment by Zexuz** [comment]
Great! I have been swamp myself, but thank you for looking in to it
