### ISSUE TITLE
grpc-web support

### ISSUE THREAD

**Issue by jackielii** [uw-labs/bloomrpc#72]
Would love to see this gets prioritised.

Do you accept contribute on this matter? We love this tool, but when it comes to grpc-web, we can't find anything easy to use.

**Comment by fenos** [comment]
@jackielii Thanks a lots for this issue!

I've busy lately hence the late reply, apologise.

I'd love contributions on this matter! Let's have a chat together on the slack channel if you can and let's make this happen.

**Comment by jackielii** [comment]
@fenos I can't seem to join slack. Been busy recently, barely have any spare time. Please invite me on slack, we can talk further. My email: jackie.space at gmail doc com

**Comment by johanbrandhorst** [comment]
@jackielii there's a grpc-web Chrome extension available now, might be of interest: https://github.com/grpc/grpc-web/issues/317#issuecomment-489420737

**Comment by danieleades** [comment]
This would be really incredible. My use case is to serve a UI from an embedded gRPC server for allowing third-party developers to hack around with the endpoints

**Comment by johanbrandhorst** [comment]
@danieleades Maybe https://github.com/fullstorydev/grpcui can do what you want

**Comment by danieleades** [comment]
It did indeed! I've got that up and running now. It's not as pretty though...

**Comment by RahulRathodGitHub** [comment]
Would really love to see this happen.

**Comment by gary-lo** [comment]
Any updates on this? @jackielii @fenos ?

**Comment by jackielii** [comment]
We've been using this for months now. If you need it you can build from
source yourself

**Comment by jackielii** [comment]
closed via #271
