### ISSUE TITLE
Add an About dialog box

### ISSUE THREAD

**Issue by djensen47** [uw-labs/bloomrpc#73]
It would be great to have an an "About" item on the Help menu. The dialog box at the very least should have the version number of BloomRPC but you could also include the same information that VS Code has:

![image](https://user-images.githubusercontent.com/527865/56463062-1de5ab80-6382-11e9-9f96-561a69e05173.png)

And a nice to have is to check to see if an update is available.

---

BTW, thank you for building BloomRPC, it's super helpful and works really well. Indispensable for gRPC development.

**Comment by fenos** [comment]
Hi @djensen47 I totally agree that can be a nice dialog box!

Unfortunately i don't have a windows machine available at the moment, not sure i can implement this any time soon.

Any help will be appreciated

**Comment by djensen47** [comment]
Isn't this an Electron app? Isn't there a way to do a cross-platform dialog box?

I think something like this should be available for all platforms not just Windows.

**Comment by fenos** [comment]
@djensen47 Ah I see! I though it was specific to windows. Cool let's look into it
