### ISSUE TITLE
Add ability to open a service method in multiple tabs

### ISSUE THREAD

**Issue by Trevor-L** [uw-labs/bloomrpc#74]
Currently when selecting a service method on it loads in one tab only.  Please add the ability via a double click on the service method (or other mechanism sic duplicate a tab) to allow a service method to be open in multiple tabs.

**Comment by fenos** [comment]
@Trevor-L Yes - This can be a nice upcoming feature

**Comment by tim-bm** [comment]
Hi, I've made a PR for this #194
