### ISSUE TITLE
Error parsing request message: bloomrpc does not like google.protobuf.Struct

### ISSUE THREAD

**Issue by carstenlenz** [uw-labs/bloomrpc#80]
Hey,
thanks for you really cool tool :)

One issue we noticed:
When a request message contains a `google.protobuf.Struct` field, you get the "Error parsing request message" error in BloomRPC.

Commenting out the struct will make it work.

I attached a sample `.proto`.

Cheers
Carsten
[sample_proto.zip](https://github.com/uw-labs/bloomrpc/files/3190184/sample_proto.zip)

**Comment by fenos** [comment]
Hi @carstenlenz!

Thanks for reporting the issue. Yes I've noticed there isn't in this list: https://github.com/uw-labs/bloomrpc/tree/master/static/google/protobuf

I'll be adding it shortly

**Comment by wsushmita** [comment]
@fenos still facing error
 `{
  "error": "Error parsing the request message, please report the problem sharing the offending protofile"
}`

proto message:
```
message Example {
  string Type = 1;
  google.protobuf.Value Response = 2;
}
```
