### ISSUE TITLE
Compress the preview image

### ISSUE THREAD

**Issue by lnquy** [uw-labs/bloomrpc#88]
Hi,
The preview GIF image in the README file is too big (41.5MB), that make it very slow when viewing this repo without a good connection.
I used [GifCompressor](https://gifcompressor.com/) to compress the image and it can be compressed up to 76% (~10MB, still big but a lot better now).

Not sure if it can help but I attached the compressed image here so you can use it or can just record another one with compression on.
Also, it would be better if you can capture mouse cursor in preview.

![editor-preview-min](https://user-images.githubusercontent.com/18606262/58448022-b06f2c80-8130-11e9-88fb-2e70c500ac14.gif)

Keep up your good work.
Thanks

**Comment by fenos** [comment]
@lnquy Fair enough! Thank you for the suggestion! I'll be updating the gif with the one you provided for now.

Do you have any suggested software to record GIF good quality with low weight?

**Comment by lnquy** [comment]
I'm not sure if I can suggest a good software for you as I never used MacOS before.
I used to use [Peek](https://github.com/phw/peek) on Ubuntu but it also produces a quite big GIF file.
So I think you can just recording using your old tool then try some GIF compression sites (like [GifCompressor](https://gifcompressor.com/) as I mentioned above).
