### ISSUE TITLE
How to import dependent protos

### ISSUE THREAD

**Issue by chandresh-pancholi** [uw-labs/bloomrpc#91]
Hi 

I have two directories 1. proto 2. grpc
all the grpc services have written in grpc directory. when i try importing grpc services to bloomrpc it says Temp.proto not found. I have already added the absolute path.

Absolute path: $HOME/grpc-core/src/main/proto/com.grpc.test/proto/v0
v0 directory has all the proto which was used by grpc services.
please help me out.

**Comment by chandresh-pancholi** [comment]
figured out.

**Comment by qaisjp** [comment]
Next time please share the solution instead of just saying "figured it out" and then closing an issue.

Solution:

- set "import paths" (next to refresh button)
- then press the plus button and select one of the protos
- the proto and its dependencies will show up in the sidebar

**Comment by DenisBarzanov** [comment]
yes, first you set the path to the base proto folder and only then do you click the green button to add the protos
