### ISSUE TITLE
Metadata Format

### ISSUE THREAD

**Issue by jaybyrrd** [uw-labs/bloomrpc#93]
I cannot for the life of me find an example of how to format the metadata and am simply looking for someone to pass me a resource. Thanks!

**Comment by fenos** [comment]
@jaybyrrd JSON format:

```
{
    "Authorization": "token"
}
```

in the metadata tab at the bottom

**Comment by krishna-birla** [comment]
Thank you, love you. I just wasted so much time for this, I should really start reading documentation/googling instead of hit and trial LOL.
