### ISSUE TITLE
Name resolution failure for insecure client on localhost

### ISSUE THREAD

**Issue by nphmuller** [uw-labs/bloomrpc#95]
Windows 10 1903
BloomRPC 1.3.1
electron: 4.0.3
chrome: 69.0.3497.106
node: 10.11.0
v8: 6.9.427.24-electron.0

When I try to talk to a gRPC server running on localhost, I always get the following response. Even though other gRPC clients work:
```
{
  "error": "14 UNAVAILABLE: Name resolution failure"
}
```

Repro:
``` cmd
git clone https://github.com/grpc/grpc-web
cd grpc-web
docker-compose pull
docker-compose up -d node-server
```
Server now runs on http://localhost:9090

In BloomRPC, now load the proto file in `grpc-web\packages\grpc-web\test\protos\echo.proto`
And send the following request to `http://localhost:9090`:
```
{
  "message": "Hello"
}
```
Now the error above is written to the Response field.

**Comment by fenos** [comment]
Mmmh interesting, I’ll double check that and see if it’s an internal issue in the mean time have you tried to use the local ip? 

127.0.0.1 or 0.0.0.0 and see if that resolve your GRPC call

**Comment by nphmuller** [comment]
Already tried 127.0.0.1. It also didn't work.
Didn't think to try 0.0.0.0, but I just tried it and it didn't work either. Neither did my full local ip address (192.168.x.x)

Using `telnet localhost 9090`, a connection opens just fine.

**Comment by fenos** [comment]
mmmmh that's very strange. I have no problem sending requests from bloomrpc to a local server.

try the following and see if that works:

`npm install bloomrpc-mock`

then from your terminal do:

```
bloomrpc-mock yourprotofilepath.proto
```

this will create a gRPC server on port 3009. 

then from bloomrpc try to call this mock server with any of the ip or localhost. Let me know what you get

**Comment by nphmuller** [comment]
Okay, just got it to work. The problem was that I wrote `http://` before the server name.
So `http://localhost:9090/xxx` doesn't work, but `localhost:9090/xxx` does work.

Do you think this is worth improving in the feature? If so, I'll change the issue name and first post. Else I'll close the issue.

**Comment by fenos** [comment]
@nphmuller Ahh, using the `http` protocol prefix surely wouldn't practically work since gRPC is protocol per se totally different from http. 

gRPC also resolve only hostnames and ip addresses without any protocol prefix ex :`grpc://` 

The only use of HTTP2 that gRPC does is for its transport mechanism, but the encoding and decoding 
it's proprietary to the protocol.

Welcome to the gRPC ecosystem!

**Comment by nphmuller** [comment]
Okay, thanks! No promises, but if I were to make a PR that would check for a protocol in the address bar and output an error that makes it more obvious what's going on (`Protocol not support in server address`, or something like it), would you consider accepting it?

**Comment by fenos** [comment]
Interesting idea, 
Although, I think that the validation in the address input wouldn't bring much of a value to the editor.

It's like if you try to type in the browser url a different protocol ex `udp://` - `tcp://` other then `http` / `https` it would just say it can't reach it. 

Let's keep it like this at the moment. If we find out that other new gRPC folks are typing `http` more often than not, then we can reconsider it.

I surely appreciated the idea!

**Comment by nphmuller** [comment]
Okay, thanks for the input!

**Comment by akhterm** [comment]
@fenos Having same issue on insecure localhost and tried below paths and it does not work, with and without http both did not work, Please advise further

> 127.0.01:50051/Greet.Greeter/SayHello
> localhost:50051/Greet.Greeter/SayHello 
> 0.0.00:50051/Greet.Greeter/SayHello

```
{
  "error": "14 UNAVAILABLE: Name resolution failure"
}
```

**Comment by nphmuller** [comment]
Have you tries if it works via bloomrpc-mock, as @fenos commented?
What happens id you try to connect via a tool like telnet (telnet localhost 50051)?

**Comment by akhterm** [comment]
@nphmuller telnet is working fine. In addition, I have tested gRpc Server with Client side and working good. Below code got response from Server
BloomRpc is giving **_"error": "14 UNAVAILABLE: Name resolution failure"_**
Please advise further 
```
        private static async Task greetService()
        {
           var channel = new Channel(_host, _port, ChannelCredentials.Insecure);
            var client = new Greeter.GreeterClient(channel);
            var user = "Mak";

            HelloReply reply = await client.SayHelloAsync(new HelloRequest {
                Name = user
            });
            Console.WriteLine("Greeting: " + reply.Message);
          await channel.ShutdownAsync();
        }
```

**Comment by nphmuller** [comment]
Wait, are you saying that the bloomrpc application is outputting the error, or your c# client app? This repo is about the bloomrpc application only.

But since this issue is closed anyway, I can give it a shot. What’s the value of _host and _port in the sample you posted?

**Comment by fenos** [comment]
Hi @akhterm im suspecting you are using the wrong address to connect to your GRPC service.

You just need to use the address of your service without any other suffix. Bloomrpc is smart enough to call your GRPC functions.

Try only this:

localhost:50051 
127.0.0.1:50051
0.0.0.0:50051

Without anything else

**Comment by akhterm** [comment]
@fenos It work like charm without any prefix and suffix. Thanks man!
